# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-93431646-e1ee-4d34-ab25-73f5d8effb4a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-93431646-e1ee-4d34-ab25-73f5d8effb4a".device = "/dev/disk/by-uuid/93431646-e1ee-4d34-ab25-73f5d8effb4a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F127-CD52";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a521d434-1610-444f-964f-b8b17e920ac5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
